const Colors = {
  primary: '#E85D3A',
  primaryLight: '#F4845F',
  primaryDark: '#C94A2A',
  primaryGlow: 'rgba(232, 93, 58, 0.12)',
  secondary: '#1A7A6D',
  secondaryLight: '#2A9D8F',
  secondaryDark: '#14605A',
  accent: '#F2A93B',
  accentLight: '#F5C06A',
  background: '#FAFAF7',
  backgroundSecondary: '#F0ECE6',
  card: '#FFFFFF',
  cardBorder: '#EEEAD5',
  cardShadow: 'rgba(60, 40, 20, 0.06)',
  text: '#191919',
  textSecondary: '#636366',
  textTertiary: '#A0A0A5',
  textInverse: '#FFFFFF',
  border: '#E5E0D8',
  divider: '#F2EDE5',
  success: '#30D158',
  warning: '#FF9F0A',
  error: '#FF3B30',
  overlay: 'rgba(28, 28, 30, 0.5)',
  tabIconDefault: '#AEAEB2',
  tabBar: '#FFFFFF',
  tabBarBorder: '#E8E4DC',
  light: {
    text: '#191919',
    background: '#FAFAF7',
    tint: '#E85D3A',
    tabIconDefault: '#AEAEB2',
    tabIconSelected: '#E85D3A',
  },
  shadow: {
    small: {
      shadowColor: '#1C1C1E',
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.06,
      shadowRadius: 3,
      elevation: 1,
    },
    medium: {
      shadowColor: '#1C1C1E',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.08,
      shadowRadius: 12,
      elevation: 3,
    },
    large: {
      shadowColor: '#1C1C1E',
      shadowOffset: { width: 0, height: 8 },
      shadowOpacity: 0.12,
      shadowRadius: 24,
      elevation: 6,
    },
  },
};

export default Colors;
